services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PHP_EXTENSION_XDEBUG: 1
      XDEBUG_CONFIG: 'client_host=host.docker.internal remote_enable=1 profiler_enable=0'
      PHP_IDE_CONFIG: "serverName=Docker"
    command: ["php", "./examples/main.php"]
    volumes:
      - ./:/app
    networks:
      - yahooauc-net

networks:
  yahooauc-net:
    name: yahooauc-net
